package com.vishalgupta.photoselector.data.format

import com.sun.jna.Platform
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assume.assumeTrue
import org.junit.Test
import java.nio.file.Files
import java.nio.file.Path

/**
 * Decodes a real HEIC fixture (generated by `sips` under build/heic-probe/) through [HeicDecoder]'s
 * macOS ImageIO bridge. macOS-only: skipped via [assumeTrue] elsewhere. The fixture is a 400x300
 * RGB gradient converted to HEIC; the source generation lives in the HEIC support work, not the repo.
 */
class HeicDecoderTest {

    private val fixture: Path = Path.of("build/heic-probe/fixture.heic")

    @Test
    fun decodesHeicToFullSizeBgra() = runBlocking {
        assumeTrue("macOS-only HEIC decode", Platform.isMac())
        assumeTrue("HEIC fixture present", Files.exists(fixture))

        val decoded = HeicDecoder().decode(fixture, targetMaxDimensionPx = null)

        assertEquals(400, decoded.width)
        assertEquals(300, decoded.height)
        assertEquals(400 * 300 * 4, decoded.bgraBytes.size)
        // The gradient has non-zero colour everywhere; a fully-zero buffer would mean a failed draw.
        assertTrue("decoded pixels should not be all zero", decoded.bgraBytes.any { it.toInt() != 0 })
    }

    @Test
    fun downscalesToTargetLongEdge() = runBlocking {
        assumeTrue("macOS-only HEIC decode", Platform.isMac())
        assumeTrue("HEIC fixture present", Files.exists(fixture))

        val decoded = HeicDecoder().decode(fixture, targetMaxDimensionPx = 200)

        // Longer edge (400) capped to 200; aspect ratio preserved -> 200x150.
        assertEquals(200, decoded.width)
        assertEquals(150, decoded.height)
        assertEquals(200 * 150 * 4, decoded.bgraBytes.size)
    }
}
